#!/bin/sh -eu

FORCE_BUILD=true

REMOTE=origin
BRANCH=master
BUILD_DIR=public

$FORCE_BUILD || [ -z "$(git status -s)" ] || {
    echo "The working directory is dirty. Please commit any pending changes."
    exit 1
}

echo "clean old build..."
rm -rf $BUILD_DIR
mkdir $BUILD_DIR
git worktree prune
rm -rf .git/worktrees/$BUILD_DIR/
git worktree add -B $BRANCH $BUILD_DIR $REMOTE/$BRANCH
rm -rf $BUILD_DIR/*

echo "make new..."
hugo

echo "commit any updates..."
cd $BUILD_DIR && git add --all && git commit -m "publishing site changes"
