baseURL = "https://jkeifer.github.io/"
languageCode = "en-us"
title = "lost in tab"
theme = "minimal"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false
    lineNumbersInTable = false
    tabWidth = 4

[params]
mainSections = ["posts"]
author = "Jarrett Keifer"
email = ""
description = 'Network and GIS Software Engineer in the Pacific NW'
postcss = false
# Include the author name in the <title> of articles
includeAuthorInTitle = true
disableAttribution = true

[[params.social]]
icon = "github-circle"
url = "https://github.com/jkeifer/"

[[params.social]]
icon = "linkedin"
url = "https://linkedin.com/in/jarrettkeifer"
