baseURL = "https://teotl.dev/"
languageCode = "en-us"
title = "Lost in Tab"
theme = "minimal"

[pagination]
  pagerSize = 25

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false
    lineNumbersInTable = false
    tabWidth = 4

[params]
mainSections = ["posts"]
author = "Jarrett Keifer"
#email = ""
#description = 'Network and GIS Software Engineer in the Pacific NW'
postcss = false
# Include the author name in the <title> of articles
includeAuthorInTitle = true
disableAttribution = true

[related]
  threshold = 80
  includeNewer = true
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10

[[params.social]]
icon = "github-circle"
url = "https://github.com/jkeifer/"

[[params.social]]
icon = "linkedin"
url = "https://linkedin.com/in/jarrettkeifer"
